import { ICountryData } from '../types';
import { CountryName } from '../types/countryKeys';

export const countryData: { [key in CountryName]: ICountryData } = {
  Afghanistan: {
    name: 'Afghanistan',
    density: '60',
    abbreviation: 'AF',
    area: '652,230',
    callingCode: '93',
    capital: 'Kabul',
    currencyCode: 'AFN',
    largestCity: 'Kabul',
    lifeExpectancy: '64.5',
    minimumWageInDollars: '$0.43 ',
    language: 'Pashto',
    population: '38,041,754',
    taxRate: '71.40%',
  },
  Albania: {
    name: 'Albania',
    density: '105',
    abbreviation: 'AL',
    area: '28,748',
    callingCode: '355',
    capital: 'Tirana',
    currencyCode: 'ALL',
    largestCity: 'Tirana',
    lifeExpectancy: '78.5',
    minimumWageInDollars: '$1.12 ',
    language: 'Albanian',
    population: '2,854,191',
    taxRate: '36.60%',
  },
  Algeria: {
    name: 'Algeria',
    density: '18',
    abbreviation: 'DZ',
    area: '2,381,741',
    callingCode: '213',
    capital: 'Algiers',
    currencyCode: 'DZD',
    largestCity: 'Algiers',
    lifeExpectancy: '76.7',
    minimumWageInDollars: '$0.95 ',
    language: 'Arabic',
    population: '43,053,054',
    taxRate: '66.10%',
  },
  Andorra: {
    name: 'Andorra',
    density: '164',
    abbreviation: 'AD',
    area: '468',
    callingCode: '376',
    capital: 'Andorra la Vella',
    currencyCode: 'EUR',
    largestCity: 'Andorra la Vella',
    lifeExpectancy: '',
    minimumWageInDollars: '$6.63 ',
    language: 'Catalan',
    population: '77,142',
    taxRate: '',
  },
  Angola: {
    name: 'Angola',
    density: '26',
    abbreviation: 'AO',
    area: '1,246,700',
    callingCode: '244',
    capital: 'Luanda',
    currencyCode: 'AOA',
    largestCity: 'Luanda',
    lifeExpectancy: '60.8',
    minimumWageInDollars: '$0.71 ',
    language: 'Portuguese',
    population: '31,825,295',
    taxRate: '49.10%',
  },
  'Antigua and Barbuda': {
    name: 'Antigua and Barbuda',
    density: '223',
    abbreviation: 'AG',
    area: '443',
    callingCode: '1',
    capital: "St. John's, Saint John",
    currencyCode: 'XCD',
    largestCity: "St. John's, Saint John",
    lifeExpectancy: '76.9',
    minimumWageInDollars: '$3.04 ',
    language: 'English',
    population: '97,118',
    taxRate: '43.00%',
  },
  Argentina: {
    name: 'Argentina',
    density: '17',
    abbreviation: 'AR',
    area: '2,780,400',
    callingCode: '54',
    capital: 'Buenos Aires',
    currencyCode: 'ARS',
    largestCity: 'Buenos Aires',
    lifeExpectancy: '76.5',
    minimumWageInDollars: '$3.35 ',
    language: 'Spanish',
    population: '44,938,712',
    taxRate: '106.30%',
  },
  Armenia: {
    name: 'Armenia',
    density: '104',
    abbreviation: 'AM',
    area: '29,743',
    callingCode: '374',
    capital: 'Yerevan',
    currencyCode: 'AMD',
    largestCity: 'Yerevan',
    lifeExpectancy: '74.9',
    minimumWageInDollars: '$0.66 ',
    language: 'Armenian',
    population: '2,957,731',
    taxRate: '22.60%',
  },
  Australia: {
    name: 'Australia',
    density: '3',
    abbreviation: 'AU',
    area: '7,741,220',
    callingCode: '61',
    capital: 'Canberra',
    currencyCode: 'AUD',
    largestCity: 'Sydney',
    lifeExpectancy: '82.7',
    minimumWageInDollars: '$13.59 ',
    language: 'None',
    population: '25,766,605',
    taxRate: '47.40%',
  },
  Austria: {
    name: 'Austria',
    density: '109',
    abbreviation: 'AT',
    area: '83,871',
    callingCode: '43',
    capital: 'Vienna',
    currencyCode: 'EUR',
    largestCity: 'Vienna',
    lifeExpectancy: '81.6',
    minimumWageInDollars: '',
    language: 'German',
    population: '8,877,067',
    taxRate: '51.40%',
  },
  Azerbaijan: {
    name: 'Azerbaijan',
    density: '123',
    abbreviation: 'AZ',
    area: '86,600',
    callingCode: '994',
    capital: 'Baku',
    currencyCode: 'AZN',
    largestCity: 'Baku',
    lifeExpectancy: '72.9',
    minimumWageInDollars: '$0.47 ',
    language: 'Azerbaijani language',
    population: '10,023,318',
    taxRate: '40.70%',
  },
  Bahamas: {
    name: 'The Bahamas',
    density: '39',
    abbreviation: 'BS',
    area: '13,880',
    callingCode: '1',
    capital: 'Nassau, Bahamas',
    currencyCode: '',
    largestCity: 'Nassau, Bahamas',
    lifeExpectancy: '73.8',
    minimumWageInDollars: '$5.25 ',
    language: 'English',
    population: '389,482',
    taxRate: '33.80%',
  },
  Bahrain: {
    name: 'Bahrain',
    density: '2,239',
    abbreviation: 'BH',
    area: '765',
    callingCode: '973',
    capital: 'Manama',
    currencyCode: 'BHD',
    largestCity: 'Riffa',
    lifeExpectancy: '77.2',
    minimumWageInDollars: '',
    language: 'Arabic',
    population: '1,501,635',
    taxRate: '13.80%',
  },
  Bangladesh: {
    name: 'Bangladesh',
    density: '1,265',
    abbreviation: 'BD',
    area: '148,460',
    callingCode: '880',
    capital: 'Dhaka',
    currencyCode: 'BDT',
    largestCity: 'Dhaka',
    lifeExpectancy: '72.3',
    minimumWageInDollars: '$0.51 ',
    language: 'Bengali',
    population: '167,310,838',
    taxRate: '33.40%',
  },
  Barbados: {
    name: 'Barbados',
    density: '668',
    abbreviation: 'BB',
    area: '430',
    callingCode: '1',
    capital: 'Bridgetown',
    currencyCode: 'BBD',
    largestCity: 'Bridgetown',
    lifeExpectancy: '79.1',
    minimumWageInDollars: '$3.13 ',
    language: 'English',
    population: '287,025',
    taxRate: '35.60%',
  },
  Belarus: {
    name: 'Belarus',
    density: '47',
    abbreviation: 'BY',
    area: '207,600',
    callingCode: '375',
    capital: 'Minsk',
    currencyCode: 'BYN',
    largestCity: 'Minsk',
    lifeExpectancy: '74.2',
    minimumWageInDollars: '$1.49 ',
    language: 'Russian',
    population: '9,466,856',
    taxRate: '53.30%',
  },
  Belgium: {
    name: 'Belgium',
    density: '383',
    abbreviation: 'BE',
    area: '30,528',
    callingCode: '32',
    capital: 'City of Brussels',
    currencyCode: 'EUR',
    largestCity: 'Brussels',
    lifeExpectancy: '81.6',
    minimumWageInDollars: '$10.31 ',
    language: 'French',
    population: '11,484,055',
    taxRate: '55.40%',
  },
  Belize: {
    name: 'Belize',
    density: '17',
    abbreviation: 'BZ',
    area: '22,966',
    callingCode: '501',
    capital: 'Belmopan',
    currencyCode: 'BZD',
    largestCity: 'Belize City',
    lifeExpectancy: '74.5',
    minimumWageInDollars: '$1.65 ',
    language: 'English',
    population: '390,353',
    taxRate: '31.10%',
  },
  Benin: {
    name: 'Benin',
    density: '108',
    abbreviation: 'BJ',
    area: '112,622',
    callingCode: '229',
    capital: 'Porto-Novo',
    currencyCode: 'XOF',
    largestCity: 'Cotonou',
    lifeExpectancy: '61.5',
    minimumWageInDollars: '$0.39 ',
    language: 'French',
    population: '11,801,151',
    taxRate: '48.90%',
  },
  Bhutan: {
    name: 'Bhutan',
    density: '20',
    abbreviation: 'BT',
    area: '38,394',
    callingCode: '975',
    capital: 'Thimphu',
    currencyCode: '',
    largestCity: 'Thimphu',
    lifeExpectancy: '71.5',
    minimumWageInDollars: '$0.32 ',
    language: 'Dzongkha',
    population: '727,145',
    taxRate: '35.30%',
  },
  Bolivia: {
    name: 'Bolivia',
    density: '11',
    abbreviation: 'BO',
    area: '1,098,581',
    callingCode: '591',
    capital: 'Sucre',
    currencyCode: 'BOB',
    largestCity: 'Santa Cruz de la Sierra',
    lifeExpectancy: '71.2',
    minimumWageInDollars: '$1.36 ',
    language: 'Spanish',
    population: '11,513,100',
    taxRate: '83.70%',
  },
  'Bosnia and Herz.': {
    name: 'Bosnia and Herzegovina',
    density: '64',
    abbreviation: 'BA',
    area: '51,197',
    callingCode: '387',
    capital: 'Sarajevo',
    currencyCode: 'BAM',
    largestCity: 'Tuzla Canton',
    lifeExpectancy: '77.3',
    minimumWageInDollars: '$1.04 ',
    language: 'Bosnian',
    population: '3,301,000',
    taxRate: '23.70%',
  },
  Botswana: {
    name: 'Botswana',
    density: '4',
    abbreviation: 'BW',
    area: '581,730',
    callingCode: '267',
    capital: 'Gaborone',
    currencyCode: 'BWP',
    largestCity: 'Gaborone',
    lifeExpectancy: '69.3',
    minimumWageInDollars: '$0.29 ',
    language: 'English',
    population: '2,346,179',
    taxRate: '25.10%',
  },
  Brazil: {
    name: 'Brazil',
    density: '25',
    abbreviation: 'BR',
    area: '8,515,770',
    callingCode: '55',
    capital: 'Brasília',
    currencyCode: 'BRL',
    largestCity: 'São Paulo',
    lifeExpectancy: '75.7',
    minimumWageInDollars: '$1.53 ',
    language: 'Portuguese',
    population: '212,559,417',
    taxRate: '65.10%',
  },
  Brunei: {
    name: 'Brunei',
    density: '83',
    abbreviation: 'BN',
    area: '5,765',
    callingCode: '673',
    capital: 'Bandar Seri Begawan',
    currencyCode: 'BND',
    largestCity: '',
    lifeExpectancy: '75.7',
    minimumWageInDollars: '',
    language: 'Malay',
    population: '433,285',
    taxRate: '8.00%',
  },
  Bulgaria: {
    name: 'Bulgaria',
    density: '64',
    abbreviation: 'BG',
    area: '110,879',
    callingCode: '359',
    capital: 'Sofia',
    currencyCode: 'BGN',
    largestCity: 'Sofia',
    lifeExpectancy: '74.9',
    minimumWageInDollars: '$1.57 ',
    language: 'Bulgarian',
    population: '6,975,761',
    taxRate: '28.30%',
  },
  'Burkina Faso': {
    name: 'Burkina Faso',
    density: '76',
    abbreviation: 'BF',
    area: '274,200',
    callingCode: '226',
    capital: 'Ouagadougou',
    currencyCode: 'XOF',
    largestCity: 'Ouagadougou',
    lifeExpectancy: '61.2',
    minimumWageInDollars: '$0.34 ',
    language: 'French',
    population: '20,321,378',
    taxRate: '41.30%',
  },
  Burundi: {
    name: 'Burundi',
    density: '463',
    abbreviation: 'BI',
    area: '27,830',
    callingCode: '257',
    capital: 'Bujumbura',
    currencyCode: 'BIF',
    largestCity: 'Bujumbura',
    lifeExpectancy: '61.2',
    minimumWageInDollars: '',
    language: 'Kirundi',
    population: '11,530,580',
    taxRate: '41.20%',
  },
  "Côte d'Ivoire": {
    name: 'Ivory Coast',
    density: '83',
    abbreviation: 'CI',
    area: '322,463',
    callingCode: '225',
    capital: 'Yamoussoukro',
    currencyCode: 'XOF',
    largestCity: 'Abidjan',
    lifeExpectancy: '57.4',
    minimumWageInDollars: '$0.36 ',
    language: 'French',
    population: '25,716,544',
    taxRate: '50.10%',
  },
  'Cape Verde': {
    name: 'Cape Verde',
    density: '138',
    abbreviation: 'CV',
    area: '4,033',
    callingCode: '238',
    capital: 'Praia',
    currencyCode: 'CVE',
    largestCity: 'Praia',
    lifeExpectancy: '72.8',
    minimumWageInDollars: '$0.68 ',
    language: 'Portuguese',
    population: '483,628',
    taxRate: '37.50%',
  },
  Cambodia: {
    name: 'Cambodia',
    density: '95',
    abbreviation: 'KH',
    area: '181,035',
    callingCode: '855',
    capital: 'Phnom Penh',
    currencyCode: '',
    largestCity: 'Phnom Penh',
    lifeExpectancy: '69.6',
    minimumWageInDollars: '',
    language: 'Khmer language',
    population: '16,486,542',
    taxRate: '23.10%',
  },
  Cameroon: {
    name: 'Cameroon',
    density: '56',
    abbreviation: 'CM',
    area: '475,440',
    callingCode: '237',
    capital: 'Yaoundé',
    currencyCode: 'XAF',
    largestCity: 'Douala',
    lifeExpectancy: '58.9',
    minimumWageInDollars: '$0.35 ',
    language: 'French',
    population: '25,876,380',
    taxRate: '57.70%',
  },
  Canada: {
    name: 'Canada',
    density: '4',
    abbreviation: 'CA',
    area: '9,984,670',
    callingCode: '1',
    capital: 'Ottawa',
    currencyCode: 'CAD',
    largestCity: 'Toronto',
    lifeExpectancy: '81.9',
    minimumWageInDollars: '$9.51 ',
    language: 'French',
    population: '36,991,981',
    taxRate: '24.50%',
  },
  'Central African Rep.': {
    name: 'Central African Republic',
    density: '8',
    abbreviation: 'CF',
    area: '622,984',
    callingCode: '236',
    capital: 'Bangui',
    currencyCode: '',
    largestCity: 'Bangui',
    lifeExpectancy: '52.8',
    minimumWageInDollars: '$0.37 ',
    language: 'French',
    population: '4,745,185',
    taxRate: '73.30%',
  },
  Chad: {
    name: 'Chad',
    density: '13',
    abbreviation: 'TD',
    area: '1,284,000',
    callingCode: '235',
    capital: "N'Djamena",
    currencyCode: 'XAF',
    largestCity: "N'Djamena",
    lifeExpectancy: '54',
    minimumWageInDollars: '$0.60 ',
    language: 'French',
    population: '15,946,876',
    taxRate: '63.50%',
  },
  Chile: {
    name: 'Chile',
    density: '26',
    abbreviation: 'CL',
    area: '756,096',
    callingCode: '56',
    capital: 'Santiago',
    currencyCode: 'CLP',
    largestCity: 'Santiago',
    lifeExpectancy: '80',
    minimumWageInDollars: '$2.00 ',
    language: 'Spanish',
    population: '18,952,038',
    taxRate: '34.00%',
  },
  China: {
    name: 'China',
    density: '153',
    abbreviation: 'CN',
    area: '9,596,960',
    callingCode: '86',
    capital: 'Beijing',
    currencyCode: 'CNY',
    largestCity: 'Shanghai',
    lifeExpectancy: '77',
    minimumWageInDollars: '$0.87 ',
    language: 'Standard Chinese',
    population: '1,397,715,000',
    taxRate: '59.20%',
  },
  Colombia: {
    name: 'Colombia',
    density: '46',
    abbreviation: 'CO',
    area: '1,138,910',
    callingCode: '57',
    capital: 'Bogotá',
    currencyCode: 'COP',
    largestCity: 'Bogotá',
    lifeExpectancy: '77.1',
    minimumWageInDollars: '$1.23 ',
    language: 'Spanish',
    population: '50,339,443',
    taxRate: '71.20%',
  },
  Comoros: {
    name: 'Comoros',
    density: '467',
    abbreviation: 'KM',
    area: '2,235',
    callingCode: '269',
    capital: 'Moroni, Comoros',
    currencyCode: 'KMF',
    largestCity: 'Moroni, Comoros',
    lifeExpectancy: '64.1',
    minimumWageInDollars: '$0.71 ',
    language: 'French',
    population: '850,886',
    taxRate: '219.60%',
  },
  Congo: {
    name: 'Congo',
    density: '16',
    abbreviation: '',
    area: '342,000',
    callingCode: '242',
    capital: 'Brazzaville',
    currencyCode: 'XAF',
    largestCity: 'Brazzaville',
    lifeExpectancy: '64.3',
    minimumWageInDollars: '$0.88 ',
    language: 'French',
    population: '5,380,508',
    taxRate: '54.30%',
  },
  'Costa Rica': {
    name: 'Costa Rica',
    density: '100',
    abbreviation: 'CR',
    area: '51,100',
    callingCode: '506',
    capital: 'San Jose',
    currencyCode: 'CRC',
    largestCity: 'San Jose',
    lifeExpectancy: '80.1',
    minimumWageInDollars: '$1.84 ',
    language: 'Spanish',
    population: '5,047,561',
    taxRate: '58.30%',
  },
  Croatia: {
    name: 'Croatia',
    density: '73',
    abbreviation: 'HR',
    area: '56,594',
    callingCode: '385',
    capital: 'Zagreb',
    currencyCode: 'HRK',
    largestCity: 'Zagreb',
    lifeExpectancy: '78.1',
    minimumWageInDollars: '$2.92 ',
    language: 'Croatian',
    population: '4,067,500',
    taxRate: '20.50%',
  },
  Cuba: {
    name: 'Cuba',
    density: '106',
    abbreviation: 'CU',
    area: '110,860',
    callingCode: '53',
    capital: 'Havana',
    currencyCode: 'CUP',
    largestCity: 'Havana',
    lifeExpectancy: '78.7',
    minimumWageInDollars: '$0.05 ',
    language: 'Spanish',
    population: '11,333,483',
    taxRate: '',
  },
  Cyprus: {
    name: 'Cyprus',
    density: '131',
    abbreviation: 'CY',
    area: '9,251',
    callingCode: '357',
    capital: 'Nicosia',
    currencyCode: 'EUR',
    largestCity: 'Nicosia',
    lifeExpectancy: '80.8',
    minimumWageInDollars: '',
    language: 'Greek',
    population: '1,198,575',
    taxRate: '22.40%',
  },
  Czechia: {
    name: 'Czech Republic',
    density: '139',
    abbreviation: 'CZ',
    area: '78,867',
    callingCode: '420',
    capital: 'Prague',
    currencyCode: 'CZK',
    largestCity: 'Prague',
    lifeExpectancy: '79',
    minimumWageInDollars: '$3.00 ',
    language: 'Czech',
    population: '10,669,709',
    taxRate: '46.10%',
  },
  'Dem. Rep. Congo': {
    name: 'Dem. Rep. Congo',
    density: '40',
    abbreviation: 'CD',
    area: '2,344,858',
    callingCode: '243',
    capital: 'Kinshasa',
    currencyCode: 'CDF',
    largestCity: 'Kinshasa',
    lifeExpectancy: '60.4',
    minimumWageInDollars: '$0.18 ',
    language: 'French',
    population: '86,790,567',
    taxRate: '50.70%',
  },
  Denmark: {
    name: 'Denmark',
    density: '137',
    abbreviation: 'DK',
    area: '43,094',
    callingCode: '45',
    capital: 'Copenhagen',
    currencyCode: 'DKK',
    largestCity: 'Copenhagen',
    lifeExpectancy: '81',
    minimumWageInDollars: '',
    language: 'Danish',
    population: '5,818,553',
    taxRate: '23.80%',
  },
  Djibouti: {
    name: 'Djibouti',
    density: '43',
    abbreviation: 'DJ',
    area: '23,200',
    callingCode: '253',
    capital: 'Djibouti City',
    currencyCode: 'DJF',
    largestCity: 'Djibouti City',
    lifeExpectancy: '66.6',
    minimumWageInDollars: '',
    language: 'French',
    population: '973,560',
    taxRate: '37.90%',
  },
  Dominica: {
    name: 'Dominica',
    density: '96',
    abbreviation: 'DM',
    area: '751',
    callingCode: '1',
    capital: 'Roseau',
    currencyCode: 'XCD',
    largestCity: 'Roseau',
    lifeExpectancy: '76.6',
    minimumWageInDollars: '$1.48 ',
    language: 'English',
    population: '71,808',
    taxRate: '32.60%',
  },
  'Dominican Rep.': {
    name: 'Dominican Republic',
    density: '225',
    abbreviation: 'DO',
    area: '48,670',
    callingCode: '1',
    capital: 'Santo Domingo',
    currencyCode: 'DOP',
    largestCity: 'Santo Domingo',
    lifeExpectancy: '73.9',
    minimumWageInDollars: '$0.40 ',
    language: 'Spanish',
    population: '10,738,958',
    taxRate: '48.80%',
  },
  Ecuador: {
    name: 'Ecuador',
    density: '71',
    abbreviation: 'EC',
    area: '283,561',
    callingCode: '593',
    capital: 'Quito',
    currencyCode: 'USD',
    largestCity: 'Quito',
    lifeExpectancy: '76.8',
    minimumWageInDollars: '$2.46 ',
    language: 'Spanish',
    population: '17,373,662',
    taxRate: '34.40%',
  },
  Egypt: {
    name: 'Egypt',
    density: '103',
    abbreviation: 'EG',
    area: '1,001,450',
    callingCode: '20',
    capital: 'Cairo',
    currencyCode: 'EGP',
    largestCity: 'Cairo',
    lifeExpectancy: '71.8',
    minimumWageInDollars: '',
    language: 'Modern Standard Arabic',
    population: '100,388,073',
    taxRate: '44.40%',
  },
  'El Salvador': {
    name: 'El Salvador',
    density: '313',
    abbreviation: 'SV',
    area: '21,041',
    callingCode: '503',
    capital: 'San Salvador',
    currencyCode: '',
    largestCity: 'San Salvador',
    lifeExpectancy: '73.1',
    minimumWageInDollars: '$0.50 ',
    language: 'Spanish',
    population: '6,453,553',
    taxRate: '36.40%',
  },
  'Eq. Guinea': {
    name: 'Equatorial Guinea',
    density: '50',
    abbreviation: 'GQ',
    area: '28,051',
    callingCode: '240',
    capital: 'Malabo',
    currencyCode: 'XAF',
    largestCity: 'Malabo',
    lifeExpectancy: '58.4',
    minimumWageInDollars: '$1.05 ',
    language: 'Spanish',
    population: '1,355,986',
    taxRate: '79.40%',
  },
  Eritrea: {
    name: 'Eritrea',
    density: '35',
    abbreviation: 'ER',
    area: '117,600',
    callingCode: '291',
    capital: 'Asmara',
    currencyCode: 'ERN',
    largestCity: 'Asmara',
    lifeExpectancy: '65.9',
    minimumWageInDollars: '',
    language: 'Tigrinya',
    population: '6,333,135',
    taxRate: '83.70%',
  },
  Estonia: {
    name: 'Estonia',
    density: '31',
    abbreviation: 'EE',
    area: '45,228',
    callingCode: '372',
    capital: 'Tallinn',
    currencyCode: 'EUR',
    largestCity: 'Tallinn',
    lifeExpectancy: '78.2',
    minimumWageInDollars: '$3.14 ',
    language: 'Estonian',
    population: '1,331,824',
    taxRate: '47.80%',
  },
  eSwatini: {
    name: 'Eswatini',
    density: '67',
    abbreviation: '',
    area: '17,364',
    callingCode: '268',
    capital: 'Mbabane',
    currencyCode: '',
    largestCity: 'Mbabane',
    lifeExpectancy: '',
    minimumWageInDollars: '',
    language: 'English',
    population: '1,093,238',
    taxRate: '',
  },
  Ethiopia: {
    name: 'Ethiopia',
    density: '115',
    abbreviation: 'ET',
    area: '1,104,300',
    callingCode: '251',
    capital: 'Addis Ababa',
    currencyCode: 'ETB',
    largestCity: 'Addis Ababa',
    lifeExpectancy: '66.2',
    minimumWageInDollars: '',
    language: 'Amharic',
    population: '112,078,730',
    taxRate: '37.70%',
  },
  Fiji: {
    name: 'Fiji',
    density: '49',
    abbreviation: 'FJ',
    area: '18,274',
    callingCode: '679',
    capital: 'Suva',
    currencyCode: 'FJD',
    largestCity: 'Suva',
    lifeExpectancy: '67.3',
    minimumWageInDollars: '$1.28 ',
    language: 'Fiji Hindi',
    population: '889,953',
    taxRate: '32.10%',
  },
  Finland: {
    name: 'Finland',
    density: '18',
    abbreviation: 'FI',
    area: '338,145',
    callingCode: '358',
    capital: 'Helsinki',
    currencyCode: 'EUR',
    largestCity: 'Helsinki',
    lifeExpectancy: '81.7',
    minimumWageInDollars: '',
    language: 'Swedish',
    population: '5,520,314',
    taxRate: '36.60%',
  },
  France: {
    name: 'France',
    density: '119',
    abbreviation: 'FR',
    area: '643,801',
    callingCode: '33',
    capital: 'Paris',
    currencyCode: 'EUR',
    largestCity: 'Paris',
    lifeExpectancy: '82.5',
    minimumWageInDollars: '$11.16 ',
    language: 'French',
    population: '67,059,887',
    taxRate: '60.70%',
  },
  Gabon: {
    name: 'Gabon',
    density: '9',
    abbreviation: 'GA',
    area: '267,667',
    callingCode: '241',
    capital: 'Libreville',
    currencyCode: 'XAF',
    largestCity: 'Libreville',
    lifeExpectancy: '66.2',
    minimumWageInDollars: '$1.46 ',
    language: 'French',
    population: '2,172,579',
    taxRate: '47.10%',
  },
  Gambia: {
    name: 'The Gambia',
    density: '239',
    abbreviation: 'GM',
    area: '11,300',
    callingCode: '220',
    capital: 'Banjul',
    currencyCode: 'GMD',
    largestCity: 'Serekunda',
    lifeExpectancy: '61.7',
    minimumWageInDollars: '$0.13 ',
    language: 'English',
    population: '2,347,706',
    taxRate: '48.40%',
  },
  Georgia: {
    name: 'Georgia',
    density: '57',
    abbreviation: 'GE',
    area: '69,700',
    callingCode: '995',
    capital: 'Tbilisi',
    currencyCode: 'GEL',
    largestCity: 'Tbilisi',
    lifeExpectancy: '73.6',
    minimumWageInDollars: '$0.05 ',
    language: 'Georgian',
    population: '3,720,382',
    taxRate: '9.90%',
  },
  Germany: {
    name: 'Germany',
    density: '240',
    abbreviation: 'DE',
    area: '357,022',
    callingCode: '49',
    capital: 'Berlin',
    currencyCode: 'EUR',
    largestCity: 'Berlin',
    lifeExpectancy: '80.9',
    minimumWageInDollars: '$9.99 ',
    language: 'German',
    population: '83,132,799',
    taxRate: '48.80%',
  },
  Ghana: {
    name: 'Ghana',
    density: '137',
    abbreviation: 'GH',
    area: '238,533',
    callingCode: '233',
    capital: 'Accra',
    currencyCode: 'GHS',
    largestCity: 'Accra',
    lifeExpectancy: '63.8',
    minimumWageInDollars: '$0.27 ',
    language: 'English',
    population: '30,792,608',
    taxRate: '55.40%',
  },
  Greece: {
    name: 'Greece',
    density: '81',
    abbreviation: 'GR',
    area: '131,957',
    callingCode: '30',
    capital: 'Athens',
    currencyCode: 'EUR',
    largestCity: 'Macedonia',
    lifeExpectancy: '81.3',
    minimumWageInDollars: '$4.46 ',
    language: 'Greek',
    population: '10,716,322',
    taxRate: '51.90%',
  },
  Grenada: {
    name: 'Grenada',
    density: '331',
    abbreviation: 'GD',
    area: '349',
    callingCode: '1',
    capital: "St. George's, Grenada",
    currencyCode: 'XCD',
    largestCity: "St. George's, Grenada",
    lifeExpectancy: '72.4',
    minimumWageInDollars: '',
    language: 'English',
    population: '112,003',
    taxRate: '47.80%',
  },
  Guatemala: {
    name: 'Guatemala',
    density: '167',
    abbreviation: 'GT',
    area: '108,889',
    callingCode: '502',
    capital: 'Guatemala City',
    currencyCode: 'GTQ',
    largestCity: 'Guatemala City',
    lifeExpectancy: '74.1',
    minimumWageInDollars: '$1.60 ',
    language: 'Spanish',
    population: '16,604,026',
    taxRate: '35.20%',
  },
  Guinea: {
    name: 'Guinea',
    density: '53',
    abbreviation: 'GN',
    area: '245,857',
    callingCode: '224',
    capital: 'Conakry',
    currencyCode: 'GNF',
    largestCity: 'Kankan',
    lifeExpectancy: '61.2',
    minimumWageInDollars: '',
    language: 'French',
    population: '12,771,246',
    taxRate: '69.30%',
  },
  'Guinea-Bissau': {
    name: 'Guinea-Bissau',
    density: '70',
    abbreviation: 'GW',
    area: '36,125',
    callingCode: '245',
    capital: 'Bissau',
    currencyCode: 'XOF',
    largestCity: 'Bissau',
    lifeExpectancy: '58',
    minimumWageInDollars: '$0.16 ',
    language: 'Portuguese',
    population: '1,920,922',
    taxRate: '45.50%',
  },
  Guyana: {
    name: 'Guyana',
    density: '4',
    abbreviation: 'GY',
    area: '214,969',
    callingCode: '592',
    capital: 'Georgetown, Guyana',
    currencyCode: 'GYD',
    largestCity: 'Georgetown, Guyana',
    lifeExpectancy: '69.8',
    minimumWageInDollars: '$0.98 ',
    language: 'English',
    population: '782,766',
    taxRate: '30.60%',
  },
  Haiti: {
    name: 'Haiti',
    density: '414',
    abbreviation: 'HT',
    area: '27,750',
    callingCode: '509',
    capital: 'Port-au-Prince',
    currencyCode: 'HTG',
    largestCity: 'Port-au-Prince',
    lifeExpectancy: '63.7',
    minimumWageInDollars: '$0.25 ',
    language: 'French',
    population: '11,263,077',
    taxRate: '42.70%',
  },
  'Vatican City': {
    name: 'Vatican City',
    density: '2,003',
    abbreviation: '',
    area: '0',
    callingCode: '379',
    capital: 'Vatican City',
    currencyCode: 'EUR',
    largestCity: '',
    lifeExpectancy: '',
    minimumWageInDollars: '',
    language: 'Italian',
    population: '836',
    taxRate: '',
  },
  Honduras: {
    name: 'Honduras',
    density: '89',
    abbreviation: 'HN',
    area: '112,090',
    callingCode: '504',
    capital: 'Tegucigalpa',
    currencyCode: 'HNL',
    largestCity: 'Tegucigalpa',
    lifeExpectancy: '75.1',
    minimumWageInDollars: '$1.01 ',
    language: 'Spanish',
    population: '9,746,117',
    taxRate: '39.10%',
  },
  Hungary: {
    name: 'Hungary',
    density: '107',
    abbreviation: 'HU',
    area: '93,028',
    callingCode: '36',
    capital: 'Budapest',
    currencyCode: 'HUF',
    largestCity: 'Budapest',
    lifeExpectancy: '75.8',
    minimumWageInDollars: '$2.62 ',
    language: 'Hungarian',
    population: '9,769,949',
    taxRate: '37.90%',
  },
  Iceland: {
    name: 'Iceland',
    density: '3',
    abbreviation: 'IS',
    area: '103,000',
    callingCode: '354',
    capital: 'Reykjavik',
    currencyCode: 'ISK',
    largestCity: 'Reykjavik',
    lifeExpectancy: '82.7',
    minimumWageInDollars: '',
    language: 'Icelandic',
    population: '361,313',
    taxRate: '31.90%',
  },
  India: {
    name: 'India',
    density: '464',
    abbreviation: 'IN',
    area: '3,287,263',
    callingCode: '91',
    capital: 'New Delhi',
    currencyCode: 'INR',
    largestCity: 'Kurebhar',
    lifeExpectancy: '69.4',
    minimumWageInDollars: '$0.30 ',
    language: 'Hindi',
    population: '1,366,417,754',
    taxRate: '49.70%',
  },
  Indonesia: {
    name: 'Indonesia',
    density: '151',
    abbreviation: 'ID',
    area: '1,904,569',
    callingCode: '62',
    capital: 'Jakarta',
    currencyCode: 'IDR',
    largestCity: 'Kalimantan',
    lifeExpectancy: '71.5',
    minimumWageInDollars: '$0.48 ',
    language: 'Indonesian',
    population: '270,203,917',
    taxRate: '30.10%',
  },
  Iran: {
    name: 'Iran',
    density: '52',
    abbreviation: 'IR',
    area: '1,648,195',
    callingCode: '98',
    capital: 'Tehran',
    currencyCode: 'IRR',
    largestCity: 'Tehran',
    lifeExpectancy: '76.5',
    minimumWageInDollars: '$1.58 ',
    language: 'Persian',
    population: '82,913,906',
    taxRate: '44.70%',
  },
  Iraq: {
    name: 'Iraq',
    density: '93',
    abbreviation: 'IQ',
    area: '438,317',
    callingCode: '964',
    capital: 'Baghdad',
    currencyCode: 'IQD',
    largestCity: 'Baghdad',
    lifeExpectancy: '70.5',
    minimumWageInDollars: '$1.24 ',
    language: 'Arabic',
    population: '39,309,783',
    taxRate: '30.80%',
  },
  Ireland: {
    name: 'Republic of Ireland',
    density: '72',
    abbreviation: '',
    area: '70,273',
    callingCode: '353',
    capital: 'Dublin',
    currencyCode: 'EUR',
    largestCity: 'Connacht',
    lifeExpectancy: '82.3',
    minimumWageInDollars: '$10.79 ',
    language: 'Irish',
    population: '5,007,069',
    taxRate: '26.10%',
  },
  Israel: {
    name: 'Israel',
    density: '400',
    abbreviation: 'IL',
    area: '20,770',
    callingCode: '972',
    capital: 'Jerusalem',
    currencyCode: 'ILS',
    largestCity: 'Jerusalem',
    lifeExpectancy: '82.8',
    minimumWageInDollars: '$7.58 ',
    language: 'Hebrew',
    population: '9,053,300',
    taxRate: '25.30%',
  },
  Italy: {
    name: 'Italy',
    density: '206',
    abbreviation: 'IT',
    area: '301,340',
    callingCode: '39',
    capital: 'Rome',
    currencyCode: 'EUR',
    largestCity: 'Rome',
    lifeExpectancy: '82.9',
    minimumWageInDollars: '',
    language: 'Italian',
    population: '60,297,396',
    taxRate: '59.10%',
  },
  Jamaica: {
    name: 'Jamaica',
    density: '273',
    abbreviation: 'JM',
    area: '10,991',
    callingCode: '1876',
    capital: 'Kingston, Jamaica',
    currencyCode: 'JMD',
    largestCity: 'Kingston, Jamaica',
    lifeExpectancy: '74.4',
    minimumWageInDollars: '$1.33 ',
    language: 'Jamaican English',
    population: '2,948,279',
    taxRate: '35.10%',
  },
  Japan: {
    name: 'Japan',
    density: '347',
    abbreviation: 'JP',
    area: '377,944',
    callingCode: '81',
    capital: 'Tokyo',
    currencyCode: '',
    largestCity: 'Tokyo',
    lifeExpectancy: '84.2',
    minimumWageInDollars: '$6.77 ',
    language: 'None',
    population: '126,226,568',
    taxRate: '46.70%',
  },
  Jordan: {
    name: 'Jordan',
    density: '115',
    abbreviation: 'JO',
    area: '89,342',
    callingCode: '962',
    capital: 'Amman',
    currencyCode: 'JOD',
    largestCity: 'Amman',
    lifeExpectancy: '74.4',
    minimumWageInDollars: '$1.49 ',
    language: 'Arabic',
    population: '10,101,694',
    taxRate: '28.60%',
  },
  Kazakhstan: {
    name: 'Kazakhstan',
    density: '7',
    abbreviation: 'KZ',
    area: '2,724,900',
    callingCode: '7',
    capital: 'Astana',
    currencyCode: 'KZT',
    largestCity: 'Almaty',
    lifeExpectancy: '73.2',
    minimumWageInDollars: '$0.41 ',
    language: 'Russian',
    population: '18,513,930',
    taxRate: '28.40%',
  },
  Kenya: {
    name: 'Kenya',
    density: '94',
    abbreviation: 'KE',
    area: '580,367',
    callingCode: '254',
    capital: 'Nairobi',
    currencyCode: 'KES',
    largestCity: 'Nairobi',
    lifeExpectancy: '66.3',
    minimumWageInDollars: '$0.25 ',
    language: 'Swahili',
    population: '52,573,973',
    taxRate: '37.20%',
  },
  Kiribati: {
    name: 'Kiribati',
    density: '147',
    abbreviation: 'KI',
    area: '811',
    callingCode: '686',
    capital: 'South Tarawa',
    currencyCode: 'AUD',
    largestCity: 'South Tarawa',
    lifeExpectancy: '68.1',
    minimumWageInDollars: '',
    language: 'English',
    population: '117,606',
    taxRate: '32.70%',
  },
  Kuwait: {
    name: 'Kuwait',
    density: '240',
    abbreviation: 'KW',
    area: '17,818',
    callingCode: '965',
    capital: 'Kuwait City',
    currencyCode: 'KWD',
    largestCity: 'Kuwait City',
    lifeExpectancy: '75.4',
    minimumWageInDollars: '$0.95 ',
    language: 'Modern Standard Arabic',
    population: '4,207,083',
    taxRate: '13.00%',
  },
  Kyrgyzstan: {
    name: 'Kyrgyzstan',
    density: '34',
    abbreviation: 'KG',
    area: '199,951',
    callingCode: '996',
    capital: 'Bishkek',
    currencyCode: 'KGS',
    largestCity: 'Bishkek',
    lifeExpectancy: '71.4',
    minimumWageInDollars: '$0.09 ',
    language: 'Russian',
    population: '6,456,900',
    taxRate: '29.00%',
  },
  Laos: {
    name: 'Laos',
    density: '32',
    abbreviation: 'LA',
    area: '236,800',
    callingCode: '856',
    capital: 'Vientiane',
    currencyCode: 'LAK',
    largestCity: 'Vientiane',
    lifeExpectancy: '67.6',
    minimumWageInDollars: '$0.83 ',
    language: 'Lao',
    population: '7,169,455',
    taxRate: '24.10%',
  },
  Latvia: {
    name: 'Latvia',
    density: '30',
    abbreviation: 'LV',
    area: '64,589',
    callingCode: '371',
    capital: 'Riga',
    currencyCode: 'EUR',
    largestCity: 'Riga',
    lifeExpectancy: '74.7',
    minimumWageInDollars: '$2.80 ',
    language: 'Latvian',
    population: '1,912,789',
    taxRate: '38.10%',
  },
  Lebanon: {
    name: 'Lebanon',
    density: '667',
    abbreviation: 'LB',
    area: '10,400',
    callingCode: '961',
    capital: 'Beirut',
    currencyCode: 'LBP',
    largestCity: 'Tripoli, Lebanon',
    lifeExpectancy: '78.9',
    minimumWageInDollars: '$2.15 ',
    language: 'Arabic',
    population: '6,855,713',
    taxRate: '32.20%',
  },
  Lesotho: {
    name: 'Lesotho',
    density: '71',
    abbreviation: 'LS',
    area: '30,355',
    callingCode: '266',
    capital: 'Maseru',
    currencyCode: '',
    largestCity: 'Maseru',
    lifeExpectancy: '53.7',
    minimumWageInDollars: '$0.41 ',
    language: 'English',
    population: '2,125,268',
    taxRate: '13.60%',
  },
  Liberia: {
    name: 'Liberia',
    density: '53',
    abbreviation: 'LR',
    area: '111,369',
    callingCode: '231',
    capital: 'Monrovia',
    currencyCode: '',
    largestCity: 'Monrovia',
    lifeExpectancy: '63.7',
    minimumWageInDollars: '$0.17 ',
    language: 'English',
    population: '4,937,374',
    taxRate: '46.20%',
  },
  Libya: {
    name: 'Libya',
    density: '4',
    abbreviation: 'LY',
    area: '1,759,540',
    callingCode: '218',
    capital: '',
    currencyCode: 'LYD',
    largestCity: '',
    lifeExpectancy: '72.7',
    minimumWageInDollars: '$1.88 ',
    language: 'Arabic',
    population: '6,777,452',
    taxRate: '32.60%',
  },
  Liechtenstein: {
    name: 'Liechtenstein',
    density: '238',
    abbreviation: 'LI',
    area: '160',
    callingCode: '423',
    capital: 'Vaduz',
    currencyCode: 'CHF',
    largestCity: 'Schaan',
    lifeExpectancy: '83',
    minimumWageInDollars: '',
    language: 'German',
    population: '38,019',
    taxRate: '21.60%',
  },
  Lithuania: {
    name: 'Lithuania',
    density: '43',
    abbreviation: 'LT',
    area: '65,300',
    callingCode: '370',
    capital: 'Vilnius',
    currencyCode: 'EUR',
    largestCity: 'Vilnius',
    lifeExpectancy: '75.7',
    minimumWageInDollars: '$2.41 ',
    language: 'Lithuanian',
    population: '2,786,844',
    taxRate: '42.60%',
  },
  Luxembourg: {
    name: 'Luxembourg',
    density: '242',
    abbreviation: 'LU',
    area: '2,586',
    callingCode: '352',
    capital: 'Luxembourg City',
    currencyCode: 'EUR',
    largestCity: 'Luxembourg City',
    lifeExpectancy: '82.1',
    minimumWageInDollars: '$13.05 ',
    language: 'Luxembourgish',
    population: '645,397',
    taxRate: '20.40%',
  },
  Madagascar: {
    name: 'Madagascar',
    density: '48',
    abbreviation: 'MG',
    area: '587,041',
    callingCode: '261',
    capital: 'Antananarivo',
    currencyCode: 'MGA',
    largestCity: 'Antananarivo',
    lifeExpectancy: '66.7',
    minimumWageInDollars: '$0.21 ',
    language: 'French',
    population: '26,969,307',
    taxRate: '38.30%',
  },
  Malawi: {
    name: 'Malawi',
    density: '203',
    abbreviation: 'MW',
    area: '118,484',
    callingCode: '265',
    capital: 'Lilongwe',
    currencyCode: 'MWK',
    largestCity: 'Lilongwe',
    lifeExpectancy: '63.8',
    minimumWageInDollars: '$0.12 ',
    language: 'English',
    population: '18,628,747',
    taxRate: '34.50%',
  },
  Malaysia: {
    name: 'Malaysia',
    density: '99',
    abbreviation: 'MY',
    area: '329,847',
    callingCode: '60',
    capital: 'Kuala Lumpur',
    currencyCode: 'MYR',
    largestCity: 'Johor Bahru',
    lifeExpectancy: '76',
    minimumWageInDollars: '$0.93 ',
    language: 'Malaysian language',
    population: '32,447,385',
    taxRate: '38.70%',
  },
  Maldives: {
    name: 'Maldives',
    density: '1,802',
    abbreviation: 'MV',
    area: '298',
    callingCode: '960',
    capital: 'Malé',
    currencyCode: '',
    largestCity: 'Malé',
    lifeExpectancy: '78.6',
    minimumWageInDollars: '',
    language: 'Divehi',
    population: '530,953',
    taxRate: '30.20%',
  },
  Mali: {
    name: 'Mali',
    density: '17',
    abbreviation: 'ML',
    area: '1,240,192',
    callingCode: '223',
    capital: 'Bamako',
    currencyCode: 'XOF',
    largestCity: 'Bamako',
    lifeExpectancy: '58.9',
    minimumWageInDollars: '$0.23 ',
    language: 'French',
    population: '19,658,031',
    taxRate: '54.50%',
  },
  Malta: {
    name: 'Malta',
    density: '1,380',
    abbreviation: 'MT',
    area: '316',
    callingCode: '356',
    capital: 'Valletta',
    currencyCode: 'EUR',
    largestCity: 'Birkirkara',
    lifeExpectancy: '82.3',
    minimumWageInDollars: '$5.07 ',
    language: 'Maltese',
    population: '502,653',
    taxRate: '44.00%',
  },
  'Marshall Islands': {
    name: 'Marshall Islands',
    density: '329',
    abbreviation: 'MH',
    area: '181',
    callingCode: '692',
    capital: 'Majuro',
    currencyCode: 'USD',
    largestCity: 'Majuro',
    lifeExpectancy: '65.2',
    minimumWageInDollars: '$2.00 ',
    language: 'Marshallese',
    population: '58,791',
    taxRate: '65.90%',
  },
  Mauritania: {
    name: 'Mauritania',
    density: '5',
    abbreviation: 'MR',
    area: '1,030,700',
    callingCode: '222',
    capital: 'Nouakchott',
    currencyCode: 'MRU',
    largestCity: 'Nouakchott',
    lifeExpectancy: '64.7',
    minimumWageInDollars: '$0.53 ',
    language: 'Arabic',
    population: '4,525,696',
    taxRate: '67.00%',
  },
  Mauritius: {
    name: 'Mauritius',
    density: '626',
    abbreviation: 'MU',
    area: '2,040',
    callingCode: '230',
    capital: 'Port Louis',
    currencyCode: 'MUR',
    largestCity: 'Port Louis',
    lifeExpectancy: '74.4',
    minimumWageInDollars: '$0.38 ',
    language: 'French',
    population: '1,265,711',
    taxRate: '22.20%',
  },
  Mexico: {
    name: 'Mexico',
    density: '66',
    abbreviation: 'MX',
    area: '1,964,375',
    callingCode: '52',
    capital: 'Mexico City',
    currencyCode: 'MXN',
    largestCity: 'Mexico City',
    lifeExpectancy: '75',
    minimumWageInDollars: '$0.49 ',
    language: 'None',
    population: '126,014,024',
    taxRate: '55.10%',
  },
  'Federated States of Micronesia': {
    name: 'Federated States of Micronesia',
    density: '784',
    abbreviation: 'FM',
    area: '702',
    callingCode: '691',
    capital: 'Palikir',
    currencyCode: 'USD',
    largestCity: 'Palikir',
    lifeExpectancy: '67.8',
    minimumWageInDollars: '',
    language: 'English',
    population: '113,815',
    taxRate: '60.50%',
  },
  Moldova: {
    name: 'Moldova',
    density: '123',
    abbreviation: 'MD',
    area: '33,851',
    callingCode: '373',
    capital: 'Chișinău',
    currencyCode: 'MDL',
    largestCity: 'Chișinău',
    lifeExpectancy: '71.8',
    minimumWageInDollars: '$0.31 ',
    language: 'Romanian',
    population: '2,657,637',
    taxRate: '38.70%',
  },
  Monaco: {
    name: 'Monaco',
    density: '26,337',
    abbreviation: 'MC',
    area: '2',
    callingCode: '377',
    capital: 'Monaco City',
    currencyCode: 'EUR',
    largestCity: 'Monaco City',
    lifeExpectancy: '',
    minimumWageInDollars: '$11.72 ',
    language: 'French',
    population: '38,964',
    taxRate: '',
  },
  Mongolia: {
    name: 'Mongolia',
    density: '2',
    abbreviation: 'MN',
    area: '1,564,116',
    callingCode: '976',
    capital: 'Ulaanbaatar',
    currencyCode: 'MNT',
    largestCity: 'Ulaanbaatar',
    lifeExpectancy: '69.7',
    minimumWageInDollars: '$0.65 ',
    language: 'Mongolian',
    population: '3,225,167',
    taxRate: '25.70%',
  },
  Montenegro: {
    name: 'Montenegro',
    density: '47',
    abbreviation: 'ME',
    area: '13,812',
    callingCode: '382',
    capital: 'Podgorica',
    currencyCode: 'EUR',
    largestCity: 'Podgorica',
    lifeExpectancy: '76.8',
    minimumWageInDollars: '$1.23 ',
    language: 'Montenegrin language',
    population: '622,137',
    taxRate: '22.20%',
  },
  Morocco: {
    name: 'Morocco',
    density: '83',
    abbreviation: 'MA',
    area: '446,550',
    callingCode: '212',
    capital: 'Rabat',
    currencyCode: 'MAD',
    largestCity: 'Casablanca',
    lifeExpectancy: '76.5',
    minimumWageInDollars: '$1.60 ',
    language: 'Arabic',
    population: '36,910,560',
    taxRate: '45.80%',
  },
  Mozambique: {
    name: 'Mozambique',
    density: '40',
    abbreviation: 'MZ',
    area: '799,380',
    callingCode: '258',
    capital: 'Maputo',
    currencyCode: 'MZN',
    largestCity: 'Maputo',
    lifeExpectancy: '60.2',
    minimumWageInDollars: '$0.27 ',
    language: 'Portuguese',
    population: '30,366,036',
    taxRate: '36.10%',
  },
  Myanmar: {
    name: 'Myanmar',
    density: '83',
    abbreviation: 'MM',
    area: '676,578',
    callingCode: '95',
    capital: 'Naypyidaw',
    currencyCode: 'MMK',
    largestCity: 'Yangon',
    lifeExpectancy: '66.9',
    minimumWageInDollars: '$0.39 ',
    language: 'Burmese',
    population: '54,045,420',
    taxRate: '31.20%',
  },
  Namibia: {
    name: 'Namibia',
    density: '3',
    abbreviation: '',
    area: '824,292',
    callingCode: '264',
    capital: 'Windhoek',
    currencyCode: '',
    largestCity: 'Windhoek',
    lifeExpectancy: '63.4',
    minimumWageInDollars: '',
    language: 'English',
    population: '2,494,530',
    taxRate: '20.70%',
  },
  Nauru: {
    name: 'Nauru',
    density: '541',
    abbreviation: 'NR',
    area: '21',
    callingCode: '674',
    capital: 'Yaren District',
    currencyCode: 'AUD',
    largestCity: '',
    lifeExpectancy: '',
    minimumWageInDollars: '',
    language: 'English',
    population: '10,084',
    taxRate: '',
  },
  Nepal: {
    name: 'Nepal',
    density: '203',
    abbreviation: 'NP',
    area: '147,181',
    callingCode: '977',
    capital: 'Kathmandu',
    currencyCode: 'NPR',
    largestCity: 'Kathmandu',
    lifeExpectancy: '70.5',
    minimumWageInDollars: '$0.36 ',
    language: 'Nepali',
    population: '28,608,710',
    taxRate: '41.80%',
  },
  Netherlands: {
    name: 'Netherlands',
    density: '508',
    abbreviation: 'NL',
    area: '41,543',
    callingCode: '31',
    capital: 'Amsterdam',
    currencyCode: '',
    largestCity: 'Amsterdam',
    lifeExpectancy: '81.8',
    minimumWageInDollars: '$10.29 ',
    language: 'Dutch',
    population: '17,332,850',
    taxRate: '41.20%',
  },
  'New Zealand': {
    name: 'New Zealand',
    density: '18',
    abbreviation: 'NZ',
    area: '268,838',
    callingCode: '64',
    capital: 'Wellington',
    currencyCode: 'NZD',
    largestCity: 'Auckland',
    lifeExpectancy: '81.9',
    minimumWageInDollars: '$11.49 ',
    language: 'English',
    population: '4,841,000',
    taxRate: '34.60%',
  },
  Nicaragua: {
    name: 'Nicaragua',
    density: '55',
    abbreviation: 'NI',
    area: '130,370',
    callingCode: '505',
    capital: 'Managua',
    currencyCode: 'NIO',
    largestCity: 'Managua',
    lifeExpectancy: '74.3',
    minimumWageInDollars: '$0.54 ',
    language: 'Spanish',
    population: '6,545,502',
    taxRate: '60.60%',
  },
  Niger: {
    name: 'Niger',
    density: '19',
    abbreviation: 'NE',
    area: '1,267,000',
    callingCode: '227',
    capital: 'Niamey',
    currencyCode: 'XOF',
    largestCity: 'Niamey',
    lifeExpectancy: '62',
    minimumWageInDollars: '$0.29 ',
    language: 'French',
    population: '23,310,715',
    taxRate: '47.20%',
  },
  Nigeria: {
    name: 'Nigeria',
    density: '226',
    abbreviation: 'NG',
    area: '923,768',
    callingCode: '234',
    capital: 'Abuja',
    currencyCode: 'NGN',
    largestCity: 'Lagos',
    lifeExpectancy: '54.3',
    minimumWageInDollars: '$0.54 ',
    language: 'English',
    population: '200,963,599',
    taxRate: '34.80%',
  },
  'North Korea': {
    name: 'North Korea',
    density: '214',
    abbreviation: 'KP',
    area: '120,538',
    callingCode: '850',
    capital: 'Pyongyang',
    currencyCode: 'KPW',
    largestCity: 'Pyongyang',
    lifeExpectancy: '72.1',
    minimumWageInDollars: '',
    language: 'Korean',
    population: '25,666,161',
    taxRate: '',
  },
  Macedonia: {
    name: 'North Macedonia',
    density: '83',
    abbreviation: '',
    area: '25,713',
    callingCode: '389',
    capital: 'Skopje',
    currencyCode: 'MKD',
    largestCity: 'Skopje',
    lifeExpectancy: '',
    minimumWageInDollars: '',
    language: 'Macedonian',
    population: '1,836,713',
    taxRate: '',
  },
  Norway: {
    name: 'Norway',
    density: '15',
    abbreviation: 'NO',
    area: '323,802',
    callingCode: '47',
    capital: 'Oslo',
    currencyCode: 'NOK',
    largestCity: 'Oslo',
    lifeExpectancy: '82.8',
    minimumWageInDollars: '',
    language: 'Norwegian',
    population: '5,347,896',
    taxRate: '36.20%',
  },
  Oman: {
    name: 'Oman',
    density: '16',
    abbreviation: 'OM',
    area: '309,500',
    callingCode: '968',
    capital: 'Muscat',
    currencyCode: 'OMR',
    largestCity: 'Seeb',
    lifeExpectancy: '77.6',
    minimumWageInDollars: '$4.33 ',
    language: 'Arabic',
    population: '5,266,535',
    taxRate: '27.40%',
  },
  Pakistan: {
    name: 'Pakistan',
    density: '287',
    abbreviation: 'PK',
    area: '796,095',
    callingCode: '92',
    capital: 'Islamabad',
    currencyCode: 'PKR',
    largestCity: 'Karachi',
    lifeExpectancy: '67.1',
    minimumWageInDollars: '$0.69 ',
    language: 'Urdu',
    population: '216,565,318',
    taxRate: '33.90%',
  },
  Palau: {
    name: 'Palau',
    density: '39',
    abbreviation: 'PW',
    area: '459',
    callingCode: '680',
    capital: 'Ngerulmud',
    currencyCode: 'USD',
    largestCity: 'Koror',
    lifeExpectancy: '69.1',
    minimumWageInDollars: '$3.00 ',
    language: 'English',
    population: '18,233',
    taxRate: '76.60%',
  },
  'Palestinian National Authority': {
    name: 'Palestinian National Authority',
    density: '847',
    abbreviation: '',
    area: '',
    callingCode: '',
    capital: '',
    currencyCode: '',
    largestCity: '',
    lifeExpectancy: '',
    minimumWageInDollars: '',
    language: 'Arabic',
    population: '',
    taxRate: '',
  },
  Panama: {
    name: 'Panama',
    density: '58',
    abbreviation: 'PA',
    area: '75,420',
    callingCode: '507',
    capital: 'Panama City',
    currencyCode: '',
    largestCity: 'Panama City',
    lifeExpectancy: '78.3',
    minimumWageInDollars: '$1.53 ',
    language: 'Spanish',
    population: '4,246,439',
    taxRate: '37.20%',
  },
  'Papua New Guinea': {
    name: 'Papua New Guinea',
    density: '20',
    abbreviation: 'PG',
    area: '462,840',
    callingCode: '675',
    capital: 'Port Moresby',
    currencyCode: 'PGK',
    largestCity: 'Port Moresby',
    lifeExpectancy: '64.3',
    minimumWageInDollars: '$1.16 ',
    language: 'Tok Pisin',
    population: '8,776,109',
    taxRate: '37.10%',
  },
  Paraguay: {
    name: 'Paraguay',
    density: '18',
    abbreviation: 'PY',
    area: '406,752',
    callingCode: '595',
    capital: 'Asunción',
    currencyCode: 'PYG',
    largestCity: 'Ciudad del Este',
    lifeExpectancy: '74.1',
    minimumWageInDollars: '$1.55 ',
    language: 'Spanish',
    population: '7,044,636',
    taxRate: '35.00%',
  },
  Peru: {
    name: 'Peru',
    density: '26',
    abbreviation: 'PE',
    area: '1,285,216',
    callingCode: '51',
    capital: 'Lima',
    currencyCode: 'PEN',
    largestCity: 'Lima',
    lifeExpectancy: '76.5',
    minimumWageInDollars: '$1.28 ',
    language: 'Spanish',
    population: '32,510,453',
    taxRate: '36.80%',
  },
  Philippines: {
    name: 'Philippines',
    density: '368',
    abbreviation: 'PH',
    area: '300,000',
    callingCode: '63',
    capital: 'Manila',
    currencyCode: 'PHP',
    largestCity: 'Manila',
    lifeExpectancy: '71.1',
    minimumWageInDollars: '$1.12 ',
    language: 'English',
    population: '108,116,615',
    taxRate: '43.10%',
  },
  Poland: {
    name: 'Poland',
    density: '124',
    abbreviation: 'PL',
    area: '312,685',
    callingCode: '48',
    capital: 'Warsaw',
    currencyCode: 'PLN',
    largestCity: 'Warsaw',
    lifeExpectancy: '77.6',
    minimumWageInDollars: '$2.93 ',
    language: 'Polish',
    population: '37,970,874',
    taxRate: '40.80%',
  },
  Portugal: {
    name: 'Portugal',
    density: '111',
    abbreviation: 'PT',
    area: '92,212',
    callingCode: '351',
    capital: 'Lisbon',
    currencyCode: 'EUR',
    largestCity: 'Lisbon',
    lifeExpectancy: '81.3',
    minimumWageInDollars: '$3.78 ',
    language: 'Portuguese',
    population: '10,269,417',
    taxRate: '39.80%',
  },
  Qatar: {
    name: 'Qatar',
    density: '248',
    abbreviation: 'QA',
    area: '11,586',
    callingCode: '974',
    capital: 'Doha',
    currencyCode: 'QAR',
    largestCity: 'Doha',
    lifeExpectancy: '80.1',
    minimumWageInDollars: '',
    language: 'Arabic',
    population: '2,832,067',
    taxRate: '11.30%',
  },
  Romania: {
    name: 'Romania',
    density: '84',
    abbreviation: 'RO',
    area: '238,391',
    callingCode: '40',
    capital: 'Bucharest',
    currencyCode: 'RON',
    largestCity: 'Bucharest',
    lifeExpectancy: '75.4',
    minimumWageInDollars: '$2.25 ',
    language: 'Romanian',
    population: '19,356,544',
    taxRate: '20.00%',
  },
  Russia: {
    name: 'Russia',
    density: '9',
    abbreviation: 'RU',
    area: '17,098,240',
    callingCode: '7',
    capital: 'Moscow',
    currencyCode: 'RUB',
    largestCity: 'Moscow',
    lifeExpectancy: '72.7',
    minimumWageInDollars: '$0.53 ',
    language: 'Russian',
    population: '144,373,535',
    taxRate: '46.20%',
  },
  Rwanda: {
    name: 'Rwanda',
    density: '525',
    abbreviation: 'RW',
    area: '26,338',
    callingCode: '250',
    capital: 'Kigali',
    currencyCode: 'RWF',
    largestCity: 'Kigali',
    lifeExpectancy: '68.7',
    minimumWageInDollars: '',
    language: 'Swahili',
    population: '12,626,950',
    taxRate: '33.20%',
  },
  'Saint Kitts and Nevis': {
    name: 'Saint Kitts and Nevis',
    density: '205',
    abbreviation: 'KN',
    area: '261',
    callingCode: '1',
    capital: 'Basseterre',
    currencyCode: 'XCD',
    largestCity: 'Basseterre',
    lifeExpectancy: '71.3',
    minimumWageInDollars: '$3.33 ',
    language: 'English',
    population: '52,823',
    taxRate: '49.70%',
  },
  'Saint Lucia': {
    name: 'Saint Lucia',
    density: '301',
    abbreviation: 'LC',
    area: '616',
    callingCode: '1',
    capital: 'Castries',
    currencyCode: 'XCD',
    largestCity: 'Castries',
    lifeExpectancy: '76.1',
    minimumWageInDollars: '',
    language: 'English',
    population: '182,790',
    taxRate: '34.70%',
  },
  'Saint Vincent and the Grenadines': {
    name: 'Saint Vincent and the Grenadines',
    density: '284',
    abbreviation: 'VC',
    area: '389',
    callingCode: '1',
    capital: 'Kingstown',
    currencyCode: 'XCD',
    largestCity: 'Calliaqua',
    lifeExpectancy: '72.4',
    minimumWageInDollars: '$1.16 ',
    language: 'English',
    population: '100,455',
    taxRate: '37.00%',
  },
  Samoa: {
    name: 'Samoa',
    density: '70',
    abbreviation: 'WS',
    area: '2,831',
    callingCode: '685',
    capital: 'Apia',
    currencyCode: 'WST',
    largestCity: 'Apia',
    lifeExpectancy: '73.2',
    minimumWageInDollars: '$0.78 ',
    language: 'Samoan',
    population: '202,506',
    taxRate: '19.30%',
  },
  'San Marino': {
    name: 'San Marino',
    density: '566',
    abbreviation: 'SM',
    area: '61',
    callingCode: '378',
    capital: 'City of San Marino',
    currencyCode: 'EUR',
    largestCity: 'City of San Marino',
    lifeExpectancy: '85.4',
    minimumWageInDollars: '',
    language: 'Italian',
    population: '33,860',
    taxRate: '36.20%',
  },
  'São Tomé and Príncipe': {
    name: 'São Tomé and Príncipe',
    density: '228',
    abbreviation: 'ST',
    area: '964',
    callingCode: '239',
    capital: 'São Tomé',
    currencyCode: 'STN',
    largestCity: 'São Tomé',
    lifeExpectancy: '70.2',
    minimumWageInDollars: '',
    language: 'Portuguese',
    population: '215,056',
    taxRate: '37.00%',
  },
  'Saudi Arabia': {
    name: 'Saudi Arabia',
    density: '16',
    abbreviation: 'SA',
    area: '2,149,690',
    callingCode: '966',
    capital: 'Riyadh',
    currencyCode: 'SAR',
    largestCity: 'Riyadh',
    lifeExpectancy: '75',
    minimumWageInDollars: '$3.85 ',
    language: 'Arabic',
    population: '34,268,528',
    taxRate: '15.70%',
  },
  Senegal: {
    name: 'Senegal',
    density: '87',
    abbreviation: 'SN',
    area: '196,722',
    callingCode: '221',
    capital: 'Dakar',
    currencyCode: 'XOF',
    largestCity: 'Pikine',
    lifeExpectancy: '67.7',
    minimumWageInDollars: '$0.31 ',
    language: 'French',
    population: '16,296,364',
    taxRate: '44.80%',
  },
  Serbia: {
    name: 'Serbia',
    density: '100',
    abbreviation: 'RS',
    area: '77,474',
    callingCode: '381',
    capital: 'Belgrade',
    currencyCode: 'RSD',
    largestCity: 'Belgrade',
    lifeExpectancy: '75.5',
    minimumWageInDollars: '$1.57 ',
    language: 'Serbian',
    population: '6,944,975',
    taxRate: '36.60%',
  },
  Seychelles: {
    name: 'Seychelles',
    density: '214',
    abbreviation: 'SC',
    area: '455',
    callingCode: '248',
    capital: 'Victoria, Seychelles',
    currencyCode: 'SCR',
    largestCity: 'Victoria, Seychelles',
    lifeExpectancy: '72.8',
    minimumWageInDollars: '$2.00 ',
    language: 'French',
    population: '97,625',
    taxRate: '30.10%',
  },
  'Sierra Leone': {
    name: 'Sierra Leone',
    density: '111',
    abbreviation: 'SL',
    area: '71,740',
    callingCode: '232',
    capital: 'Freetown',
    currencyCode: 'SLL',
    largestCity: 'Freetown',
    lifeExpectancy: '54.3',
    minimumWageInDollars: '$0.57 ',
    language: 'English',
    population: '7,813,215',
    taxRate: '30.70%',
  },
  Singapore: {
    name: 'Singapore',
    density: '8,358',
    abbreviation: 'SG',
    area: '716',
    callingCode: '65',
    capital: '',
    currencyCode: 'SGD',
    largestCity: '',
    lifeExpectancy: '83.1',
    minimumWageInDollars: '',
    language: 'Malay',
    population: '5,703,569',
    taxRate: '21.00%',
  },
  Slovakia: {
    name: 'Slovakia',
    density: '114',
    abbreviation: 'SK',
    area: '49,035',
    callingCode: '421',
    capital: 'Bratislava',
    currencyCode: 'EUR',
    largestCity: 'Bratislava',
    lifeExpectancy: '77.2',
    minimumWageInDollars: '$3.11 ',
    language: 'Slovak',
    population: '5,454,073',
    taxRate: '49.70%',
  },
  Slovenia: {
    name: 'Slovenia',
    density: '103',
    abbreviation: 'SI',
    area: '20,273',
    callingCode: '386',
    capital: 'Ljubljana',
    currencyCode: 'EUR',
    largestCity: 'Ljubljana',
    lifeExpectancy: '81',
    minimumWageInDollars: '$5.25 ',
    language: 'Slovene language',
    population: '2,087,946',
    taxRate: '31.00%',
  },
  'Solomon Is.': {
    name: 'Solomon Islands',
    density: '25',
    abbreviation: 'SB',
    area: '28,896',
    callingCode: '677',
    capital: 'Honiara',
    currencyCode: 'SBD',
    largestCity: 'Honiara',
    lifeExpectancy: '72.8',
    minimumWageInDollars: '$0.40 ',
    language: 'English',
    population: '669,823',
    taxRate: '32.00%',
  },
  Somalia: {
    name: 'Somalia',
    density: '25',
    abbreviation: 'SO',
    area: '637,657',
    callingCode: '252',
    capital: 'Mogadishu',
    currencyCode: 'SOS',
    largestCity: 'Bosaso',
    lifeExpectancy: '57.1',
    minimumWageInDollars: '',
    language: 'Arabic',
    population: '15,442,905',
    taxRate: '',
  },
  'South Africa': {
    name: 'South Africa',
    density: '49',
    abbreviation: 'ZA',
    area: '1,219,090',
    callingCode: '27',
    capital: 'Pretoria',
    currencyCode: 'ZAR',
    largestCity: 'Johannesburg',
    lifeExpectancy: '63.9',
    minimumWageInDollars: '',
    language: 'Afrikaans',
    population: '58,558,270',
    taxRate: '29.20%',
  },
  'South Korea': {
    name: 'South Korea',
    density: '527',
    abbreviation: 'KR',
    area: '99,720',
    callingCode: '82',
    capital: 'Seoul',
    currencyCode: 'KRW',
    largestCity: 'Seoul',
    lifeExpectancy: '82.6',
    minimumWageInDollars: '$6.49 ',
    language: 'Korean',
    population: '51,709,098',
    taxRate: '33.20%',
  },
  'S. Sudan': {
    name: 'South Sudan',
    density: '18',
    abbreviation: 'SS',
    area: '644,329',
    callingCode: '211',
    capital: 'Juba',
    currencyCode: 'SSP',
    largestCity: 'Juba',
    lifeExpectancy: '57.6',
    minimumWageInDollars: '',
    language: 'English',
    population: '11,062,113',
    taxRate: '31.40%',
  },
  Spain: {
    name: 'Spain',
    density: '94',
    abbreviation: 'ES',
    area: '505,370',
    callingCode: '34',
    capital: 'Madrid',
    currencyCode: 'EUR',
    largestCity: 'Madrid',
    lifeExpectancy: '83.3',
    minimumWageInDollars: '$5.60 ',
    language: 'Spanish',
    population: '47,076,781',
    taxRate: '47.00%',
  },
  'Sri Lanka': {
    name: 'Sri Lanka',
    density: '341',
    abbreviation: 'LK',
    area: '65,610',
    callingCode: '94',
    capital: 'Colombo',
    currencyCode: 'LKR',
    largestCity: 'Colombo',
    lifeExpectancy: '76.8',
    minimumWageInDollars: '$0.35 ',
    language: 'Tamil',
    population: '21,803,000',
    taxRate: '55.20%',
  },
  Sudan: {
    name: 'Sudan',
    density: '25',
    abbreviation: 'SD',
    area: '1,861,484',
    callingCode: '249',
    capital: 'Khartoum',
    currencyCode: 'SDG',
    largestCity: 'Omdurman',
    lifeExpectancy: '65.1',
    minimumWageInDollars: '$0.41 ',
    language: 'Arabic',
    population: '42,813,238',
    taxRate: '45.40%',
  },
  Suriname: {
    name: 'Suriname',
    density: '4',
    abbreviation: 'SR',
    area: '163,820',
    callingCode: '597',
    capital: 'Paramaribo',
    currencyCode: 'SRD',
    largestCity: 'Paramaribo',
    lifeExpectancy: '71.6',
    minimumWageInDollars: '',
    language: 'Dutch',
    population: '581,372',
    taxRate: '27.90%',
  },
  Sweden: {
    name: 'Sweden',
    density: '25',
    abbreviation: 'SE',
    area: '450,295',
    callingCode: '46',
    capital: 'Stockholm',
    currencyCode: 'SEK',
    largestCity: 'Stockholm',
    lifeExpectancy: '82.5',
    minimumWageInDollars: '',
    language: 'Swedish',
    population: '10,285,453',
    taxRate: '49.10%',
  },
  Switzerland: {
    name: 'Switzerland',
    density: '219',
    abbreviation: 'CH',
    area: '41,277',
    callingCode: '41',
    capital: 'Bern',
    currencyCode: 'CHF',
    largestCity: 'Zurich',
    lifeExpectancy: '83.6',
    minimumWageInDollars: '',
    language: 'German',
    population: '8,574,832',
    taxRate: '28.80%',
  },
  Syria: {
    name: 'Syria',
    density: '95',
    abbreviation: 'SY',
    area: '185,180',
    callingCode: '963',
    capital: 'Damascus',
    currencyCode: 'SYP',
    largestCity: 'Damascus',
    lifeExpectancy: '71.8',
    minimumWageInDollars: '$1.02 ',
    language: 'Arabic',
    population: '17,070,135',
    taxRate: '42.70%',
  },
  Tajikistan: {
    name: 'Tajikistan',
    density: '68',
    abbreviation: 'TJ',
    area: '144,100',
    callingCode: '992',
    capital: 'Dushanbe',
    currencyCode: 'TJS',
    largestCity: 'Dushanbe',
    lifeExpectancy: '70.9',
    minimumWageInDollars: '$0.23 ',
    language: 'Persian',
    population: '9,321,018',
    taxRate: '67.30%',
  },
  Tanzania: {
    name: 'Tanzania',
    density: '67',
    abbreviation: 'TZ',
    area: '947,300',
    callingCode: '255',
    capital: 'Dodoma',
    currencyCode: 'TZS',
    largestCity: 'Dar es Salaam',
    lifeExpectancy: '65',
    minimumWageInDollars: '$0.09 ',
    language: 'Swahili',
    population: '58,005,463',
    taxRate: '43.80%',
  },
  Thailand: {
    name: 'Thailand',
    density: '137',
    abbreviation: 'TH',
    area: '513,120',
    callingCode: '66',
    capital: 'Bangkok',
    currencyCode: 'THB',
    largestCity: 'Bangkok',
    lifeExpectancy: '76.9',
    minimumWageInDollars: '$1.06 ',
    language: 'Thai',
    population: '69,625,582',
    taxRate: '29.50%',
  },
  'East Timor': {
    name: 'East Timor',
    density: '89',
    abbreviation: 'TL',
    area: '14,874',
    callingCode: '670',
    capital: 'Dili',
    currencyCode: 'USD',
    largestCity: 'Dili',
    lifeExpectancy: '69.3',
    minimumWageInDollars: '$0.60 ',
    language: 'Portuguese',
    population: '3,500,000',
    taxRate: '17.30%',
  },
  Togo: {
    name: 'Togo',
    density: '152',
    abbreviation: 'TG',
    area: '56,785',
    callingCode: '228',
    capital: 'Lomé',
    currencyCode: 'XOF',
    largestCity: 'Lomé',
    lifeExpectancy: '60.8',
    minimumWageInDollars: '$0.34 ',
    language: 'French',
    population: '8,082,366',
    taxRate: '48.20%',
  },
  Tonga: {
    name: 'Tonga',
    density: '147',
    abbreviation: 'TO',
    area: '747',
    callingCode: '676',
    capital: "Nuku'alofa",
    currencyCode: 'TOP',
    largestCity: "Nuku'alofa",
    lifeExpectancy: '70.8',
    minimumWageInDollars: '',
    language: 'Tongan Language',
    population: '100,209',
    taxRate: '27.50%',
  },
  'Trinidad and Tobago': {
    name: 'Trinidad and Tobago',
    density: '273',
    abbreviation: 'TT',
    area: '5,128',
    callingCode: '1',
    capital: 'Port of Spain',
    currencyCode: 'TTD',
    largestCity: 'Chaguanas',
    lifeExpectancy: '73.4',
    minimumWageInDollars: '$2.25 ',
    language: 'English',
    population: '1,394,973',
    taxRate: '40.50%',
  },
  Tunisia: {
    name: 'Tunisia',
    density: '76',
    abbreviation: 'TN',
    area: '163,610',
    callingCode: '216',
    capital: 'Tunis',
    currencyCode: 'TND',
    largestCity: 'Tunis',
    lifeExpectancy: '76.5',
    minimumWageInDollars: '$0.47 ',
    language: 'Arabic',
    population: '11,694,719',
    taxRate: '60.70%',
  },
  Turkey: {
    name: 'Turkey',
    density: '110',
    abbreviation: 'TR',
    area: '783,562',
    callingCode: '90',
    capital: 'Ankara',
    currencyCode: 'TRY',
    largestCity: 'Istanbul',
    lifeExpectancy: '77.4',
    minimumWageInDollars: '$3.45 ',
    language: 'Turkish',
    population: '83,429,615',
    taxRate: '42.30%',
  },
  Turkmenistan: {
    name: 'Turkmenistan',
    density: '13',
    abbreviation: 'TM',
    area: '488,100',
    callingCode: '993',
    capital: 'Ashgabat',
    currencyCode: 'TMT',
    largestCity: 'Ashgabat',
    lifeExpectancy: '68.1',
    minimumWageInDollars: '$0.88 ',
    language: 'Turkmen',
    population: '5,942,089',
    taxRate: '',
  },
  Tuvalu: {
    name: 'Tuvalu',
    density: '393',
    abbreviation: 'TV',
    area: '26',
    callingCode: '688',
    capital: 'Funafuti',
    currencyCode: 'AUD',
    largestCity: 'Singapore',
    lifeExpectancy: '',
    minimumWageInDollars: '',
    language: 'Tuvaluan Language',
    population: '11,646',
    taxRate: '',
  },
  Uganda: {
    name: 'Uganda',
    density: '229',
    abbreviation: 'UG',
    area: '241,038',
    callingCode: '256',
    capital: 'Kampala',
    currencyCode: 'UGX',
    largestCity: 'Buganda',
    lifeExpectancy: '63',
    minimumWageInDollars: '$0.01 ',
    language: 'Swahili',
    population: '44,269,594',
    taxRate: '33.70%',
  },
  Ukraine: {
    name: 'Ukraine',
    density: '75',
    abbreviation: 'UA',
    area: '603,550',
    callingCode: '380',
    capital: 'Kyiv',
    currencyCode: 'UAH',
    largestCity: 'Kyiv',
    lifeExpectancy: '71.6',
    minimumWageInDollars: '$0.84 ',
    language: 'Ukrainian',
    population: '44,385,155',
    taxRate: '45.20%',
  },
  'United Arab Emirates': {
    name: 'United Arab Emirates',
    density: '118',
    abbreviation: 'AE',
    area: '83,600',
    callingCode: '971',
    capital: 'Abu Dhabi',
    currencyCode: 'AED',
    largestCity: 'Dubai',
    lifeExpectancy: '77.8',
    minimumWageInDollars: '',
    language: 'Arabic',
    population: '9,770,529',
    taxRate: '15.90%',
  },
  'United Kingdom': {
    name: 'United Kingdom',
    density: '281',
    abbreviation: 'GB',
    area: '243,610',
    callingCode: '44',
    capital: 'London',
    currencyCode: 'GBP',
    largestCity: 'London',
    lifeExpectancy: '81.3',
    minimumWageInDollars: '$10.13 ',
    language: 'English',
    population: '66,834,405',
    taxRate: '30.60%',
  },
  'United States of America': {
    name: 'United States',
    density: '36',
    abbreviation: 'US',
    area: '9,833,517',
    callingCode: '1',
    capital: 'Washington, D.C.',
    currencyCode: 'USD',
    largestCity: 'New York City',
    lifeExpectancy: '78.5',
    minimumWageInDollars: '$7.25 ',
    language: 'None',
    population: '328,239,523',
    taxRate: '36.60%',
  },
  Uruguay: {
    name: 'Uruguay',
    density: '20',
    abbreviation: 'UY',
    area: '176,215',
    callingCode: '598',
    capital: 'Montevideo',
    currencyCode: 'UYU',
    largestCity: 'Montevideo',
    lifeExpectancy: '77.8',
    minimumWageInDollars: '$1.66 ',
    language: 'Spanish',
    population: '3,461,734',
    taxRate: '41.80%',
  },
  Uzbekistan: {
    name: 'Uzbekistan',
    density: '79',
    abbreviation: 'UZ',
    area: '447,400',
    callingCode: '998',
    capital: 'Tashkent',
    currencyCode: 'UZS',
    largestCity: 'Tashkent',
    lifeExpectancy: '71.6',
    minimumWageInDollars: '$0.24 ',
    language: 'Uzbek',
    population: '33,580,650',
    taxRate: '31.60%',
  },
  Vanuatu: {
    name: 'Vanuatu',
    density: '25',
    abbreviation: 'VU',
    area: '12,189',
    callingCode: '678',
    capital: 'Port Vila',
    currencyCode: 'VUV',
    largestCity: 'Port Vila',
    lifeExpectancy: '70.3',
    minimumWageInDollars: '$1.56 ',
    language: 'French',
    population: '299,882',
    taxRate: '8.50%',
  },
  Venezuela: {
    name: 'Venezuela',
    density: '32',
    abbreviation: 'VE',
    area: '912,050',
    callingCode: '58',
    capital: 'Caracas',
    currencyCode: 'VED',
    largestCity: 'Caracas',
    lifeExpectancy: '72.1',
    minimumWageInDollars: '$0.01 ',
    language: 'Spanish',
    population: '28,515,829',
    taxRate: '73.30%',
  },
  Vietnam: {
    name: 'Vietnam',
    density: '314',
    abbreviation: 'VN',
    area: '331,210',
    callingCode: '84',
    capital: 'Hanoi',
    currencyCode: 'VND',
    largestCity: 'Ho Chi Minh City',
    lifeExpectancy: '75.3',
    minimumWageInDollars: '$0.73 ',
    language: 'Vietnamese',
    population: '96,462,106',
    taxRate: '37.60%',
  },
  Yemen: {
    name: 'Yemen',
    density: '56',
    abbreviation: 'YE',
    area: '527,968',
    callingCode: '967',
    capital: 'Sanaa',
    currencyCode: 'YER',
    largestCity: 'Sanaa',
    lifeExpectancy: '66.1',
    minimumWageInDollars: '',
    language: 'Arabic',
    population: '29,161,922',
    taxRate: '26.60%',
  },
  Zambia: {
    name: 'Zambia',
    density: '25',
    abbreviation: 'ZM',
    area: '752,618',
    callingCode: '260',
    capital: 'Lusaka',
    currencyCode: 'ZMW',
    largestCity: 'Lusaka',
    lifeExpectancy: '63.5',
    minimumWageInDollars: '$0.24 ',
    language: 'English',
    population: '17,861,030',
    taxRate: '15.60%',
  },
  Zimbabwe: {
    name: 'Zimbabwe',
    density: '38',
    abbreviation: 'ZW',
    area: '390,757',
    callingCode: '263',
    capital: 'Harare',
    currencyCode: '',
    largestCity: 'Harare',
    lifeExpectancy: '61.2',
    minimumWageInDollars: '',
    language: 'Shona',
    population: '14,645,468',
    taxRate: '31.60%',
  },
};
