import { CountryName } from '../types/countryKeys';

export const CountryFacts: Record<CountryName, string[]> = {
  Afghanistan: [],
  Albania: [],
  Algeria: [],
  Andorra: [],
  Angola: [],
  'Antigua and Barbuda': [],
  Argentina: [],
  Armenia: [],
  Australia: [],
  Austria: [],
  Azerbaijan: [],
  Bahamas: [],
  Bahrain: [],
  Bangladesh: [],
  Barbados: [],
  Belarus: [],
  Belgium: [],
  Belize: [],
  Benin: [],
  Bhutan: [],
  Bolivia: [],
  'Bosnia and Herz.': [],
  Botswana: [],
  Brazil: [],
  Brunei: [],
  Bulgaria: [],
  'Burkina Faso': [],
  Burundi: [],
  "Côte d'Ivoire": [],
  'Cape Verde': [],
  Cambodia: [],
  Cameroon: [],
  Canada: [],
  'Central African Rep.': [],
  Chad: [],
  Chile: [],
  China: [],
  Colombia: [],
  Comoros: [],
  Congo: [],
  'Costa Rica': [],
  Croatia: [],
  Cuba: [],
  Cyprus: [],
  Czechia: [],
  'Dem. Rep. Congo': [],
  Denmark: [],
  Djibouti: [],
  Dominica: [],
  'Dominican Rep.': [],
  Ecuador: [],
  Egypt: [],
  'El Salvador': [],
  'Eq. Guinea': [],
  Eritrea: [],
  Estonia: [],
  eSwatini: [],
  Ethiopia: [],
  Fiji: [],
  Finland: [],
  France: [],
  Gabon: [],
  Gambia: [],
  Georgia: [],
  Germany: [],
  Ghana: [],
  Greece: [],
  Grenada: [],
  Guatemala: [],
  Guinea: [],
  'Guinea-Bissau': [],
  Guyana: [],
  Haiti: [],
  'Vatican City': [],
  Honduras: [],
  Hungary: [],
  Iceland: [],
  India: [],
  Indonesia: [],
  Iran: [],
  Iraq: [],
  Ireland: [],
  Israel: [],
  Italy: [],
  Jamaica: [],
  Japan: [],
  Jordan: [],
  Kazakhstan: [],
  Kenya: [],
  Kiribati: [],
  Kuwait: [],
  Kyrgyzstan: [],
  Laos: [],
  Latvia: [],
  Lebanon: [],
  Lesotho: [],
  Liberia: [],
  Libya: [],
  Liechtenstein: [],
  Lithuania: [],
  Luxembourg: [],
  Madagascar: [],
  Malawi: [],
  Malaysia: [],
  Maldives: [],
  Mali: [],
  Malta: [],
  'Marshall Islands': [],
  Mauritania: [],
  Mauritius: [],
  Mexico: [],
  'Federated States of Micronesia': [],
  Moldova: [],
  Monaco: [],
  Mongolia: [],
  Montenegro: [],
  Morocco: [],
  Mozambique: [],
  Myanmar: [],
  Namibia: [],
  Nauru: [],
  Nepal: [],
  Netherlands: [],
  'New Zealand': [],
  Nicaragua: [],
  Niger: [],
  Nigeria: [],
  'North Korea': [],
  Macedonia: [],
  Norway: [],
  Oman: [],
  Pakistan: [],
  Palau: [],
  'Palestinian National Authority': [],
  Panama: [],
  'Papua New Guinea': [],
  Paraguay: [],
  Peru: [],
  Philippines: [],
  Poland: [],
  Portugal: [],
  Qatar: [],
  Romania: [],
  Russia: [],
  Rwanda: [],
  'Saint Kitts and Nevis': [],
  'Saint Lucia': [],
  'Saint Vincent and the Grenadines': [],
  Samoa: [],
  'San Marino': [],
  'São Tomé and Príncipe': [],
  'Saudi Arabia': [],
  Senegal: [],
  Serbia: [],
  Seychelles: [],
  'Sierra Leone': [],
  Singapore: [],
  Slovakia: [],
  Slovenia: [],
  'Solomon Is.': [],
  Somalia: [],
  'South Africa': [],
  'South Korea': [],
  'S. Sudan': [],
  Spain: [],
  'Sri Lanka': [],
  Sudan: [],
  Suriname: [],
  Sweden: [],
  Switzerland: [],
  Syria: [],
  Tajikistan: [],
  Tanzania: [],
  Thailand: [],
  'East Timor': [],
  Togo: [],
  Tonga: [],
  'Trinidad and Tobago': [],
  Tunisia: [],
  Turkey: [],
  Turkmenistan: [],
  Tuvalu: [],
  Uganda: [],
  Ukraine: [
    'Ukraine is the second largest country in Europe in terms of total area– spanning 603.55 square km (or 233 square miles – twice the size of Italy!)',
    'UNESCO World Heritage Sites designate some of the most important parts of the world and Ukraine is lucky enough to be home to seven, including the Saint-Sophia Cathedral in the capital city of Kyiv.',
    'Although when asked to think of a Ukrainian food, many people are likely to say the humble chicken kiev (which actually was probably not invented in Ukraine at all), the national Ukrainian dish is actually borscht, a distinctive red soup made from beetroot and beef.',
    'The official language of Ukraine is of course Ukrainian, however, there are 20 different languages spoken in Ukraine. 18% of Ukrainians are English speakers.',
    'Ukraine is home to one of our favourite holiday pastimes – Easter eggs! Originally coloured and patterned using wax and dye, we have Ukraine to thank for our favourite decorative treat.',
    'Standing at 2,061 metres, Mount Hoverla, part of the Carpathian Mountains which fall into Western Ukraine, is the tallest peak in Ukraine and a popular site for extreme sports.',
    'Ukraine is the world’s largest producer of sunflower seeds, and across every part of Ukraine, you’ll see stunning fields of these yellow blooms – so many that they’d cover the entire of Slovenia if you uprooted them!',
    'Ukraine is often called the “Breadbasket of Europe” because it boasts the ideal conditions for growing wheat, and is a major producer of the stuff.',
    'One of the most unique tourist attractions in Ukraine is the so-called ‘Tunnel of Love’. A section of industrial railway that is surrounded by stunning greenery, it’s a favourite for couples who are looking for a romantic walk.',
    'Ukraine is bordered to the south by the Black Sea, and here they have control over Zymiinyi Island, known commonly as Snake Island due to the residents. It’s the only natural home of the critically endangered Golden Lancehead Pit Viper, which were trapped on the island in the last Ice Age.',
  ],
  'United Arab Emirates': [],
  'United Kingdom': [],
  'United States of America': [],
  Uruguay: [],
  Uzbekistan: [],
  Vanuatu: [],
  Venezuela: [],
  Vietnam: [],
  Yemen: [],
  Zambia: [],
  Zimbabwe: [],
};
