import { CountryName } from '../types/countryKeys';

export const countriesGoodManners: Record<CountryName, string[]> = {
  Ukraine: [
    'Take your gloves off before shaking hands',
    'Bring a gift for your hosts to express your gratitude',
    'Take your shoes off when you enter someone’s house. You may be offered slippers instead',
    'Praise your host’s cooking skills',
    'Try everything and save room for seconds! Salo (marinated ham), vareniki (dumplings with a variety of different fillings), shuba (a traditional Ukrainian herring dish), and, of course, borschtsch are highly recommended!',
    'Try to finish your food: this shows your host that you are enjoying yourself',
    'Make a toast or speech, if and when the host asks you',
    'Be sincere in your toast or speech; sincerity is appreciated',
    'Drink after a toast: refusal can appear rude or suspicious. However, it is acceptable to politely decline more alcohol after the first toast, but your glass may be refilled!',
    'Offer to help clean up after the meal, although this may be politely refused.]',
  ],
  Afghanistan: [],
  Albania: [],
  Algeria: [],
  Andorra: [],
  Angola: [],
  'Antigua and Barbuda': [],
  Argentina: [],
  Armenia: [],
  Australia: [],
  Austria: [],
  Azerbaijan: [],
  Bahamas: [],
  Bahrain: [],
  Bangladesh: [],
  Barbados: [],
  Belarus: [],
  Belgium: [],
  Belize: [],
  Benin: [],
  Bhutan: [],
  Bolivia: [],
  'Bosnia and Herz.': [],
  Botswana: [],
  Brazil: [],
  Brunei: [],
  Bulgaria: [],
  'Burkina Faso': [],
  Burundi: [],
  "Côte d'Ivoire": [],
  'Cape Verde': [],
  Cambodia: [],
  Cameroon: [],
  Canada: [],
  'Central African Rep.': [],
  Chad: [],
  Chile: [],
  China: [],
  Colombia: [],
  Comoros: [],
  Congo: [],
  'Costa Rica': [],
  Croatia: [],
  Cuba: [],
  Cyprus: [],
  Czechia: [],
  'Dem. Rep. Congo': [],
  Denmark: [],
  Djibouti: [],
  Dominica: [],
  'Dominican Rep.': [],
  Ecuador: [],
  Egypt: [],
  'El Salvador': [],
  'Eq. Guinea': [],
  Eritrea: [],
  Estonia: [],
  eSwatini: [],
  Ethiopia: [],
  Fiji: [],
  Finland: [],
  France: [],
  Gabon: [],
  Gambia: [],
  Georgia: [],
  Germany: [],
  Ghana: [],
  Greece: [],
  Grenada: [],
  Guatemala: [],
  Guinea: [],
  'Guinea-Bissau': [],
  Guyana: [],
  Haiti: [],
  'Vatican City': [],
  Honduras: [],
  Hungary: [],
  Iceland: [],
  India: [],
  Indonesia: [],
  Iran: [],
  Iraq: [],
  Ireland: [],
  Israel: [],
  Italy: [],
  Jamaica: [],
  Japan: [],
  Jordan: [],
  Kazakhstan: [],
  Kenya: [],
  Kiribati: [],
  Kuwait: [],
  Kyrgyzstan: [],
  Laos: [],
  Latvia: [],
  Lebanon: [],
  Lesotho: [],
  Liberia: [],
  Libya: [],
  Liechtenstein: [],
  Lithuania: [],
  Luxembourg: [],
  Madagascar: [],
  Malawi: [],
  Malaysia: [],
  Maldives: [],
  Mali: [],
  Malta: [],
  'Marshall Islands': [],
  Mauritania: [],
  Mauritius: [],
  Mexico: [],
  'Federated States of Micronesia': [],
  Moldova: [],
  Monaco: [],
  Mongolia: [],
  Montenegro: [],
  Morocco: [],
  Mozambique: [],
  Myanmar: [],
  Namibia: [],
  Nauru: [],
  Nepal: [],
  Netherlands: [],
  'New Zealand': [],
  Nicaragua: [],
  Niger: [],
  Nigeria: [],
  'North Korea': [],
  Macedonia: [],
  Norway: [],
  Oman: [],
  Pakistan: [],
  Palau: [],
  'Palestinian National Authority': [],
  Panama: [],
  'Papua New Guinea': [],
  Paraguay: [],
  Peru: [],
  Philippines: [],
  Poland: [],
  Portugal: [],
  Qatar: [],
  Romania: [],
  Russia: [],
  Rwanda: [],
  'Saint Kitts and Nevis': [],
  'Saint Lucia': [],
  'Saint Vincent and the Grenadines': [],
  Samoa: [],
  'San Marino': [],
  'São Tomé and Príncipe': [],
  'Saudi Arabia': [],
  Senegal: [],
  Serbia: [],
  Seychelles: [],
  'Sierra Leone': [],
  Singapore: [],
  Slovakia: [],
  Slovenia: [],
  'Solomon Is.': [],
  Somalia: [],
  'South Africa': [],
  'South Korea': [],
  'S. Sudan': [],
  Spain: [],
  'Sri Lanka': [],
  Sudan: [],
  Suriname: [],
  Sweden: [],
  Switzerland: [],
  Syria: [],
  Tajikistan: [],
  Tanzania: [],
  Thailand: [],
  'East Timor': [],
  Togo: [],
  Tonga: [],
  'Trinidad and Tobago': [],
  Tunisia: [],
  Turkey: [],
  Turkmenistan: [],
  Tuvalu: [],
  Uganda: [],
  'United Arab Emirates': [],
  'United Kingdom': [],
  'United States of America': [],
  Uruguay: [],
  Uzbekistan: [],
  Vanuatu: [],
  Venezuela: [],
  Vietnam: [],
  Yemen: [],
  Zambia: [],
  Zimbabwe: [],
};
