import { CountryName } from '../types/countryKeys';

export const countriesBadManners: Record<CountryName, string[]> = {
  Ukraine: [
    'Hand gifts over the doorstep – it’s considered bad luck.',
    'Sit or put your feet on the table.',
    'Yawn when someone is speaking or in public without covering your mouth.',
    'Start eating until everyone is sitting down at the table.',
    'Refuse to try a dish: be as adventurous as you can!',
    'Waste food, especially bread, which holds historically significance in Ukraine as a symbol of well-being and prosperity.',
    'Open the fridge or cupboards in the house without the hosts’ permission.',
    'Refuse to drink Horilka at a funeral meal. This is likely to cause offense.',
    'Whistle Indoors – it’s also considered bad luck.',
    'Blow your nose in public - this is considered rude.',
  ],
  Afghanistan: [],
  Albania: [],
  Algeria: [],
  Andorra: [],
  Angola: [],
  'Antigua and Barbuda': [],
  Argentina: [],
  Armenia: [],
  Australia: [],
  Austria: [],
  Azerbaijan: [],
  Bahamas: [],
  Bahrain: [],
  Bangladesh: [],
  Barbados: [],
  Belarus: [],
  Belgium: [],
  Belize: [],
  Benin: [],
  Bhutan: [],
  Bolivia: [],
  'Bosnia and Herz.': [],
  Botswana: [],
  Brazil: [],
  Brunei: [],
  Bulgaria: [],
  'Burkina Faso': [],
  Burundi: [],
  "Côte d'Ivoire": [],
  'Cape Verde': [],
  Cambodia: [],
  Cameroon: [],
  Canada: [],
  'Central African Rep.': [],
  Chad: [],
  Chile: [],
  China: [],
  Colombia: [],
  Comoros: [],
  Congo: [],
  'Costa Rica': [],
  Croatia: [],
  Cuba: [],
  Cyprus: [],
  Czechia: [],
  'Dem. Rep. Congo': [],
  Denmark: [],
  Djibouti: [],
  Dominica: [],
  'Dominican Rep.': [],
  Ecuador: [],
  Egypt: [],
  'El Salvador': [],
  'Eq. Guinea': [],
  Eritrea: [],
  Estonia: [],
  eSwatini: [],
  Ethiopia: [],
  Fiji: [],
  Finland: [],
  France: [],
  Gabon: [],
  Gambia: [],
  Georgia: [],
  Germany: [],
  Ghana: [],
  Greece: [],
  Grenada: [],
  Guatemala: [],
  Guinea: [],
  'Guinea-Bissau': [],
  Guyana: [],
  Haiti: [],
  'Vatican City': [],
  Honduras: [],
  Hungary: [],
  Iceland: [],
  India: [],
  Indonesia: [],
  Iran: [],
  Iraq: [],
  Ireland: [],
  Israel: [],
  Italy: [],
  Jamaica: [],
  Japan: [],
  Jordan: [],
  Kazakhstan: [],
  Kenya: [],
  Kiribati: [],
  Kuwait: [],
  Kyrgyzstan: [],
  Laos: [],
  Latvia: [],
  Lebanon: [],
  Lesotho: [],
  Liberia: [],
  Libya: [],
  Liechtenstein: [],
  Lithuania: [],
  Luxembourg: [],
  Madagascar: [],
  Malawi: [],
  Malaysia: [],
  Maldives: [],
  Mali: [],
  Malta: [],
  'Marshall Islands': [],
  Mauritania: [],
  Mauritius: [],
  Mexico: [],
  'Federated States of Micronesia': [],
  Moldova: [],
  Monaco: [],
  Mongolia: [],
  Montenegro: [],
  Morocco: [],
  Mozambique: [],
  Myanmar: [],
  Namibia: [],
  Nauru: [],
  Nepal: [],
  Netherlands: [],
  'New Zealand': [],
  Nicaragua: [],
  Niger: [],
  Nigeria: [],
  'North Korea': [],
  Macedonia: [],
  Norway: [],
  Oman: [],
  Pakistan: [],
  Palau: [],
  'Palestinian National Authority': [],
  Panama: [],
  'Papua New Guinea': [],
  Paraguay: [],
  Peru: [],
  Philippines: [],
  Poland: [],
  Portugal: [],
  Qatar: [],
  Romania: [],
  Russia: [],
  Rwanda: [],
  'Saint Kitts and Nevis': [],
  'Saint Lucia': [],
  'Saint Vincent and the Grenadines': [],
  Samoa: [],
  'San Marino': [],
  'São Tomé and Príncipe': [],
  'Saudi Arabia': [],
  Senegal: [],
  Serbia: [],
  Seychelles: [],
  'Sierra Leone': [],
  Singapore: [],
  Slovakia: [],
  Slovenia: [],
  'Solomon Is.': [],
  Somalia: [],
  'South Africa': [],
  'South Korea': [],
  'S. Sudan': [],
  Spain: [],
  'Sri Lanka': [],
  Sudan: [],
  Suriname: [],
  Sweden: [],
  Switzerland: [],
  Syria: [],
  Tajikistan: [],
  Tanzania: [],
  Thailand: [],
  'East Timor': [],
  Togo: [],
  Tonga: [],
  'Trinidad and Tobago': [],
  Tunisia: [],
  Turkey: [],
  Turkmenistan: [],
  Tuvalu: [],
  Uganda: [],
  'United Arab Emirates': [],
  'United Kingdom': [],
  'United States of America': [],
  Uruguay: [],
  Uzbekistan: [],
  Vanuatu: [],
  Venezuela: [],
  Vietnam: [],
  Yemen: [],
  Zambia: [],
  Zimbabwe: [],
};
